// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AcceptStationDialog.xaml.cs" company="">
//   
// </copyright>
// <summary>
//   Interaction logic for AcceptManagerDialog.xaml
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#region Copyright and License

// // -----------------------------------------------------------------------
// // <copyright file="AcceptStationDialog.xaml.cs" company="DemTech">
// // Copyright (C) 2013 Joseph Kiniry, DemTech, 
// // IT University of Copenhagen, Technical University of Denmark,
// // Nikolaj Aaes, Nicolai Skovvart
// // </copyright>
// // -----------------------------------------------------------------------
#endregion

namespace UI.ManagerWindows {
  using System.Net;
  using System.Windows;

  /// <summary>
  /// Interaction logic for AcceptManagerDialog.xaml
  /// </summary>
  public partial class AcceptStationDialog {
    #region Fields

    /// <summary>
    /// The typed password.
    /// </summary>
    public string TypedPassword;

    /// <summary>
    /// The _ip.
    /// </summary>
    private readonly IPEndPoint _ip;

    /// <summary>
    /// The _ui.
    /// </summary>
    private readonly UiHandler _ui;

    #endregion

    #region Constructors and Destructors

    /// <summary>
    /// Initializes a new instance of the <see cref="AcceptStationDialog"/> class. 
    /// Constructor
    /// </summary>
    /// <param name="ip">
    /// the IP address of the station to accept
    /// </param>
    /// <param name="ui">
    /// the UIHandler for this UI
    /// </param>
    public AcceptStationDialog(IPEndPoint ip, UiHandler ui) {
      this._ui = ui;
      this._ip = ip;
      this.InitializeComponent();
      this.StationLabel.Content = ip.Address.ToString();
      this.Activate();
      this.PwTextbox.Focus();
      this.OKButton.IsEnabled = false;
      this.Title = "Tilslut Station";
    }

    #endregion

    #region Methods

    /// <summary>
    /// Called when the cancel button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void CancelButtonClick(object sender, RoutedEventArgs e) {
      this.DialogResult = false;
      this.Close();
    }

    /// <summary>
    /// Called when the OK button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void OkButtonClick(object sender, RoutedEventArgs e) {
      this.TypedPassword = this.PwTextbox.Password;
      this.DialogResult = true;
      this._ui.MarkAsConnected(this._ip);
      this.Close();
    }

    /// <summary>
    /// Called when the text in the PwTextbox changes
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void PwTextboxPasswordChanged(object sender, RoutedEventArgs e) { this.OKButton.IsEnabled = this.PwTextbox.Password.Length > 0; }

    #endregion
  }
}
