// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CheckMasterPasswordDialog.xaml.cs" company="">
//   
// </copyright>
// <summary>
//   Interaction logic for CheckMasterPasswordDialog.xaml
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#region Copyright and License

// // -----------------------------------------------------------------------
// // <copyright file="CheckMasterPasswordDialog.xaml.cs" company="DemTech">
// // Copyright (C) 2013 Joseph Kiniry, DemTech, 
// // IT University of Copenhagen, Technical University of Denmark,
// // Nikolaj Aaes, Nicolai Skovvart
// // </copyright>
// // -----------------------------------------------------------------------
#endregion

namespace UI.ManagerWindows {
  using System.Windows;

  /// <summary>
  /// Interaction logic for CheckMasterPasswordDialog.xaml
  /// </summary>
  public partial class CheckMasterPasswordDialog {
    #region Fields

    /// <summary>
    /// The is cancel.
    /// </summary>
    public bool IsCancel = false;

    /// <summary>
    /// The typed password.
    /// </summary>
    public string TypedPassword;

    /// <summary>
    /// The _ui.
    /// </summary>
    private readonly UiHandler _ui;

    #endregion

    #region Constructors and Destructors

    /// <summary>
    /// Initializes a new instance of the <see cref="CheckMasterPasswordDialog"/> class. 
    /// constructor
    /// </summary>
    /// <param name="ui">
    /// the UIHandler for this UI
    /// </param>
    public CheckMasterPasswordDialog(UiHandler ui, string reason) {
      InitializeComponent();
      _ui = ui;
      PwTextbox.Focus();
      Title = "Master Password";
      AuthenticationReason.Text = reason;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Called when the cancel button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void CancelButtonClick(object sender, RoutedEventArgs e) {
      DialogResult = true;
      IsCancel = true;
      Close();
    }

    /// <summary>
    /// Called when the OK button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void OkButtonClick(object sender, RoutedEventArgs e) {
      DialogResult = _ui.IsMasterPWCorrect(PwTextbox.Password);
      TypedPassword = PwTextbox.Password;
      Close();
    }

    #endregion
  }
}
