// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MasterPasswordPage.xaml.cs" company="">
//   
// </copyright>
// <summary>
//   Interaction logic for MasterPasswordPage.xaml
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#region Copyright and License

// // -----------------------------------------------------------------------
// // <copyright file="MasterPasswordPage.xaml.cs" company="DemTech">
// // Copyright (C) 2013 Joseph Kiniry, DemTech, 
// // IT University of Copenhagen, Technical University of Denmark,
// // Nikolaj Aaes, Nicolai Skovvart
// // </copyright>
// // -----------------------------------------------------------------------
#endregion

namespace UI.ManagerWindows {
  using System.Windows;
  using System.Windows.Controls;

  /// <summary>
  /// Interaction logic for MasterPasswordPage.xaml
  /// </summary>
  public partial class MasterPasswordPage {
    #region Fields

    /// <summary>
    /// The _parent.
    /// </summary>
    private readonly Frame _parent;

    /// <summary>
    /// The _ui.
    /// </summary>
    private readonly UiHandler _ui;

    #endregion

    #region Constructors and Destructors

    /// <summary>
    /// Initializes a new instance of the <see cref="MasterPasswordPage"/> class. 
    /// Constructor
    /// </summary>
    /// <param name="parent">
    /// the frame this page is shown in
    /// </param>
    /// <param name="ui">
    /// the UIHandler for this UI
    /// </param>
    public MasterPasswordPage(Frame parent, UiHandler ui) {
      InitializeComponent();
      _parent = parent;
      _ui = ui;
      MasterPassWordLabel.Content = _ui.GeneratePassword();
    }

    #endregion

    #region Methods

    /// <summary>
    /// Called when the back button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void BackButtonClick(object sender, RoutedEventArgs e) { _parent.Navigate(new TypeChoicePage(_parent, _ui)); }

    /// <summary>
    /// Called whene the next button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void NextButtonClick(object sender, RoutedEventArgs e) { _parent.Navigate(new DataLoadPage(_parent, _ui)); }

    #endregion
  }
}
