// <copyright file="MunicipalityDOTest.FullyInitialized.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace DBComm.PexTests
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Microsoft.Pex.Framework.Generated;

    using global::DBComm.DBComm.DO;

    public partial class MunicipalityDOTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void FullyInitialized98003()
{
    MunicipalityDO municipalityDO;
    bool b;
    municipalityDO = new MunicipalityDO(new uint?(1u), "", (string)null, "");
    b = this.FullyInitialized(municipalityDO);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNotNull((object)(municipalityDO.Id));
    Assert.AreEqual<uint>(1u, (uint)((object)(municipalityDO.Id)));
    Assert.AreEqual<string>("", municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>("", municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void FullyInitialized98002()
{
    MunicipalityDO municipalityDO;
    bool b;
    municipalityDO =
      new MunicipalityDO(new uint?(128u), "", (string)null, (string)null);
    b = this.FullyInitialized(municipalityDO);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNotNull((object)(municipalityDO.Id));
    Assert.AreEqual<uint>(128u, (uint)((object)(municipalityDO.Id)));
    Assert.AreEqual<string>("", municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void FullyInitialized98001()
{
    MunicipalityDO municipalityDO;
    bool b;
    municipalityDO =
      new MunicipalityDO(new uint?(1u), (string)null, (string)null, (string)null);
    b = this.FullyInitialized(municipalityDO);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNotNull((object)(municipalityDO.Id));
    Assert.AreEqual<uint>(1u, (uint)((object)(municipalityDO.Id)));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void FullyInitialized980()
{
    MunicipalityDO municipalityDO;
    bool b;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
    b = this.FullyInitialized(municipalityDO);
    Assert.AreEqual<bool>(false, b);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
    }
}
