// <copyright file="MunicipalityDOTest.UpdateValues.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace DBComm.PexTests
{
    using System;

    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Microsoft.Pex.Framework.Generated;
    using Microsoft.Pex.Engine.Exceptions;

    using global::DBComm.DBComm.DO;

    public partial class MunicipalityDOTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void UpdateValues7104()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), "", (string)null, (string)null);
    this.UpdateValues(municipalityDO, (IDataObject)municipalityDO);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>("", municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void UpdateValues7103()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, "", (string)null);
    this.UpdateValues(municipalityDO, (IDataObject)municipalityDO);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>("", municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void UpdateValues7102()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, "");
    this.UpdateValues(municipalityDO, (IDataObject)municipalityDO);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>("", municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void UpdateValues7101()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(new uint?(1u), (string)null, (string)null, (string)null);
    this.UpdateValues(municipalityDO, (IDataObject)municipalityDO);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNotNull((object)(municipalityDO.Id));
    Assert.AreEqual<uint>(1u, (uint)((object)(municipalityDO.Id)));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
public void UpdateValues71()
{
    MunicipalityDO municipalityDO;
    municipalityDO =
      new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
    this.UpdateValues(municipalityDO, (IDataObject)municipalityDO);
    Assert.IsNotNull((object)municipalityDO);
    Assert.IsNotNull(municipalityDO.PollingStations);
    Assert.IsNull((object)(municipalityDO.Id));
    Assert.AreEqual<string>((string)null, municipalityDO.Address);
    Assert.AreEqual<string>((string)null, municipalityDO.City);
    Assert.AreEqual<string>((string)null, municipalityDO.Name);
}
[TestMethod]
[PexGeneratedBy(typeof(MunicipalityDOTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void UpdateValuesThrowsContractException338()
{
    try
    {
      MunicipalityDO municipalityDO;
      municipalityDO =
        new MunicipalityDO(default(uint?), (string)null, (string)null, (string)null);
      this.UpdateValues(municipalityDO, (IDataObject)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
