// <copyright file="PollingStationDOTest.UpdateValues.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>

namespace DBComm.PexTests
{
    using System;

    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Microsoft.Pex.Framework.Generated;
    using Microsoft.Pex.Engine.Exceptions;

    using global::DBComm.DBComm.DO;

    public partial class PollingStationDOTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PollingStationDOTest))]
public void UpdateValues7104()
{
    PollingStationDO pollingStationDO;
    pollingStationDO = new PollingStationDO
                           (default(uint?), new uint?(1u), (string)null, (string)null);
    this.UpdateValues(pollingStationDO, (IDataObject)pollingStationDO);
    Assert.IsNotNull((object)pollingStationDO);
    Assert.IsNotNull((object)(pollingStationDO.PrimaryKey));
    Assert.AreEqual<uint>(1u, (uint)((object)(pollingStationDO.PrimaryKey)));
    Assert.IsNull((object)(pollingStationDO.MunicipalityId));
    Assert.AreEqual<string>((string)null, pollingStationDO.Name);
    Assert.AreEqual<string>((string)null, pollingStationDO.Address);
    Assert.IsNotNull(pollingStationDO.Voters);
}
[TestMethod]
[PexGeneratedBy(typeof(PollingStationDOTest))]
public void UpdateValues7103()
{
    PollingStationDO pollingStationDO;
    pollingStationDO =
      new PollingStationDO(new uint?(1u), default(uint?), (string)null, "");
    this.UpdateValues(pollingStationDO, (IDataObject)pollingStationDO);
    Assert.IsNotNull((object)pollingStationDO);
    Assert.IsNull((object)(pollingStationDO.PrimaryKey));
    Assert.IsNotNull((object)(pollingStationDO.MunicipalityId));
    Assert.AreEqual<uint>(1u, (uint)((object)(pollingStationDO.MunicipalityId)));
    Assert.AreEqual<string>((string)null, pollingStationDO.Name);
    Assert.AreEqual<string>("", pollingStationDO.Address);
    Assert.IsNotNull(pollingStationDO.Voters);
}
[TestMethod]
[PexGeneratedBy(typeof(PollingStationDOTest))]
public void UpdateValues7102()
{
    PollingStationDO pollingStationDO;
    pollingStationDO =
      new PollingStationDO(default(uint?), default(uint?), "", (string)null);
    this.UpdateValues(pollingStationDO, (IDataObject)pollingStationDO);
    Assert.IsNotNull((object)pollingStationDO);
    Assert.IsNull((object)(pollingStationDO.PrimaryKey));
    Assert.IsNull((object)(pollingStationDO.MunicipalityId));
    Assert.AreEqual<string>("", pollingStationDO.Name);
    Assert.AreEqual<string>((string)null, pollingStationDO.Address);
    Assert.IsNotNull(pollingStationDO.Voters);
}
[TestMethod]
[PexGeneratedBy(typeof(PollingStationDOTest))]
public void UpdateValues7101()
{
    PollingStationDO pollingStationDO;
    pollingStationDO = new PollingStationDO
                           (new uint?(1u), default(uint?), (string)null, (string)null);
    this.UpdateValues(pollingStationDO, (IDataObject)pollingStationDO);
    Assert.IsNotNull((object)pollingStationDO);
    Assert.IsNull((object)(pollingStationDO.PrimaryKey));
    Assert.IsNotNull((object)(pollingStationDO.MunicipalityId));
    Assert.AreEqual<uint>(1u, (uint)((object)(pollingStationDO.MunicipalityId)));
    Assert.AreEqual<string>((string)null, pollingStationDO.Name);
    Assert.AreEqual<string>((string)null, pollingStationDO.Address);
    Assert.IsNotNull(pollingStationDO.Voters);
}
[TestMethod]
[PexGeneratedBy(typeof(PollingStationDOTest))]
public void UpdateValues71()
{
    PollingStationDO pollingStationDO;
    pollingStationDO = new PollingStationDO
                           (default(uint?), default(uint?), (string)null, (string)null);
    this.UpdateValues(pollingStationDO, (IDataObject)pollingStationDO);
    Assert.IsNotNull((object)pollingStationDO);
    Assert.IsNull((object)(pollingStationDO.PrimaryKey));
    Assert.IsNull((object)(pollingStationDO.MunicipalityId));
    Assert.AreEqual<string>((string)null, pollingStationDO.Name);
    Assert.AreEqual<string>((string)null, pollingStationDO.Address);
    Assert.IsNotNull(pollingStationDO.Voters);
}
[TestMethod]
[PexGeneratedBy(typeof(PollingStationDOTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void UpdateValuesThrowsContractException717()
{
    try
    {
      PollingStationDO pollingStationDO;
      pollingStationDO = new PollingStationDO
                             (default(uint?), default(uint?), (string)null, (string)null);
      this.UpdateValues(pollingStationDO, (IDataObject)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
