// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AcceptManagerDialog.xaml.cs" company="">
//   
// </copyright>
// <summary>
//   Interaction logic for AcceptManagerDialog.xaml
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#region Copyright and License

// // -----------------------------------------------------------------------
// // <copyright file="AcceptManagerDialog.xaml.cs" company="DemTech">
// // Copyright (C) 2013 Joseph Kiniry, DemTech, 
// // IT University of Copenhagen, Technical University of Denmark,
// // Nikolaj Aaes, Nicolai Skovvart
// // </copyright>
// // -----------------------------------------------------------------------
#endregion

namespace UI.StationWindows {
  using System.Net;
  using System.Windows;
  using System.Windows.Controls;

  /// <summary>
  /// Interaction logic for AcceptManagerDialog.xaml
  /// </summary>
  public partial class AcceptManagerDialog {
    #region Fields

    /// <summary>
    /// The _parent.
    /// </summary>
    private readonly Frame _parent;

    /// <summary>
    /// The _waiting for manager page.
    /// </summary>
    private readonly WaitingForManagerPage _waitingForManagerPage;

    #endregion

    #region Constructors and Destructors

    /// <summary>
    /// Initializes a new instance of the <see cref="AcceptManagerDialog"/> class. 
    /// Constructor
    /// </summary>
    /// <param name="parent">
    /// the frame this dialog was shown over
    /// </param>
    /// <param name="ip">
    /// the ip address of the Manager
    /// </param>
    /// <param name="waitingForManagerPage">
    /// the Page this dialog was shown over
    /// </param>
    public AcceptManagerDialog(Frame parent, IPEndPoint ip, WaitingForManagerPage waitingForManagerPage) {
      this.InitializeComponent();
      this._parent = parent;
      this._waitingForManagerPage = waitingForManagerPage;
      this.ManagerLabel.Content = ip.Address.ToString();
      this.Activate();
      this.PwTextbox.Focus();
      this.OKButton.IsEnabled = false;
      this.Title = "Tilslut Manager";
    }

    #endregion

    #region Methods

    /// <summary>
    /// Called when the cancel button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void CancelButtonClick(object sender, RoutedEventArgs e) {
      this.DialogResult = false;
      this.Close();
    }

    /// <summary>
    /// Called when the OK button is clicked
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void OkButtonClick(object sender, RoutedEventArgs e) {
      this._waitingForManagerPage.TypedPassword = this.PwTextbox.Password;
      this.DialogResult = true;
      this.Close();
    }

    /// <summary>
    /// Called when the text in the PwTextbox changes
    /// </summary>
    /// <param name="sender">
    /// autogenerated
    /// </param>
    /// <param name="e">
    /// autogenerated
    /// </param>
    private void PwTextboxPasswordChanged(object sender, RoutedEventArgs e) { this.OKButton.IsEnabled = this.PwTextbox.Password.Length > 0; }

    #endregion
  }
}
