// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SqLiteDatabase.cs" company="">
//   
// </copyright>
// <summary>
//   The sq lite database.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#region Copyright and License

// // -----------------------------------------------------------------------
// // <copyright file="SqLiteDatabase.cs" company="DemTech">
// // Copyright (C) 2013 Joseph Kiniry, DemTech, 
// // IT University of Copenhagen, Technical University of Denmark,
// // Nikolaj Aaes, Nicolai Skovvart
// // </copyright>
// // -----------------------------------------------------------------------
#endregion

namespace Aegis_DVL.Database {
  using System;
  using System.Collections.Generic;
  using System.Data.Common;
  using System.Data.SQLite;
  using System.Diagnostics.Contracts;
  using System.Linq;

  using Aegis_DVL.Cryptography;
  using Aegis_DVL.Data_Types;
  using Aegis_DVL.Util;

  /// <summary>
  /// The sq lite database.
  /// </summary>
  internal class SqLiteDatabase : IDatabase {
    #region Fields

    /// <summary>
    ///   The database, wrapped in an autogenerated Entities.
    /// </summary>
    private readonly Entities db;

    /// <summary>
    /// The _is disposed.
    /// </summary>
    private bool isDisposed;

    #endregion

    #region Constructors and Destructors

    /// <summary>
    /// Initializes a new instance of the <see cref="SqLiteDatabase"/> class. 
    /// May I have a new SqliteDatabase?
    /// </summary>
    /// <param name="parent">
    /// The parent station of the database.
    /// </param>
    /// <param name="filename">
    /// The name of the file where the data is stored. Defaults to Voters.sqlite.
    /// </param>
    public SqLiteDatabase(Station parent, string filename = "Voters.sqlite") {
      Contract.Requires(parent != null);
      Contract.Requires(filename != null);

      this.Parent = parent;
      string password = Crypto.GeneratePassword();
      InitDb(filename, password);

      string conStr =
        string.Format(
          "metadata=res://*/Database.VoterModel.csdl|" +
          "res://*/Database.VoterModel.ssdl|" +
          "res://*/Database.VoterModel.msl;" +
          "provider=System.Data.SQLite;" +
          "provider connection string='Data Source={0};Password={1}'", 
          filename, 
          password);
      this.db = new Entities(conStr);
      this.db.Connection.Open();
    }

    /// <summary>
    /// Finalizes an instance of the <see cref="SqLiteDatabase"/> class. 
    /// </summary>
    ~SqLiteDatabase() { this.Dispose(false); }

    #endregion

    #region Public Properties

    /// <summary>
    /// Gets the all data.
    /// </summary>
    public IEnumerable<EncryptedVoterData> AllData {
      get {
        return
          this.db.Voters.ToArray()
              .Select(
                data =>
                new EncryptedVoterData(
                  new CipherText(data.VoterNumber), 
                  new CipherText(data.CPR), 
                  new CipherText(data.BallotStatus)))
              .ToArray();
      }
    }

    /// <summary>
    /// Gets the parent.
    /// </summary>
    public Station Parent { get; private set; }

    #endregion

    #region Public Indexers

    /// <summary>
    /// The this.
    /// </summary>
    /// <param name="voternumber">
    /// The voternumber.
    /// </param>
    /// <returns>
    /// The <see cref="BallotStatus"/>.
    /// </returns>
    /// TODO: review for problems with complexity
    public BallotStatus this[VoterNumber voternumber] {
      get {
        Voter voter = GetVoter(voternumber);
        if (voter == null) return BallotStatus.Unavailable;
        CipherText encVn = this.Parent.Crypto.AsymmetricEncrypt(
          Bytes.From(voternumber.Value), this.Parent.Crypto.VoterDataEncryptionKey);
        if (!voter.VoterNumber.IsIdenticalTo(encVn)) return BallotStatus.Unavailable;
        CipherText encBallotReceived = this.Parent.Crypto.AsymmetricEncrypt(
          Bytes.From((uint)BallotStatus.Received), 
          this.Parent.Crypto.VoterDataEncryptionKey);
        return voter.BallotStatus.IsIdenticalTo(encBallotReceived)
                 ? BallotStatus.Received
                 : BallotStatus.NotReceived;
      }

      set {
        if (this.Parent.Logger != null) {
          this.Parent.Logger.Log(
            "Setting ballotstatus for voternumber=" +
            voternumber + " to " + value, 
            Level.Info);
        }

        Voter voter = GetVoter(voternumber);
        voter.BallotStatus = this.Parent.Crypto.AsymmetricEncrypt(
          Bytes.From((uint)value), this.Parent.Crypto.VoterDataEncryptionKey);
        this.db.SaveChanges();
      }
    }

    /// <summary>
    /// The this.
    /// </summary>
    /// <param name="cpr">
    /// The cpr.
    /// </param>
    /// <param name="masterPassword">
    /// The master password.
    /// </param>
    /// <returns>
    /// The <see cref="BallotStatus"/>.
    /// </returns>
    /// TODO: review for problems with complexity
    public BallotStatus this[CPR cpr, string masterPassword] {
      get {
        CipherText encBallotReceived = this.Parent.Crypto.AsymmetricEncrypt(
          Bytes.From((uint)BallotStatus.Received), this.Parent.Crypto.VoterDataEncryptionKey);
        Voter voter = GetVoter(cpr);
        if (voter == null) return BallotStatus.Unavailable;
        return voter.BallotStatus.IsIdenticalTo(encBallotReceived) ? BallotStatus.Received : BallotStatus.NotReceived;
      }

      set {
        if (this.Parent.Logger != null) {
          this.Parent.Logger.Log(
            "Setting ballotstatus for CPR=" + cpr +
            " with masterpassword to " + value, 
            Level.Info);
        }

        Voter voter = GetVoter(cpr);
        voter.BallotStatus = this.Parent.Crypto.AsymmetricEncrypt(
          Bytes.From((uint)value), this.Parent.Crypto.VoterDataEncryptionKey);
        this.db.SaveChanges();
      }
    }

    #endregion

    #region Public Methods and Operators

    /// <summary>
    /// The dispose.
    /// </summary>
    public void Dispose() {
      if (!this.isDisposed) this.Dispose(true);
      GC.SuppressFinalize(this);
    }

    /// <summary>
    /// The import.
    /// </summary>
    /// <param name="data">
    /// The data.
    /// </param>
    public void Import(IEnumerable<EncryptedVoterData> data) {
      int c = 0;
      using (DbTransaction transaction = this.db.Connection.BeginTransaction()) {
        data.ForEach(
          row => {
            this.Add(row);
            c++;
          });
        transaction.Commit();
      }

      if (this.Parent.Logger != null) this.Parent.Logger.Log("Importing data. " + c + " entries.", Level.Info);
    }

    #endregion

    #region Methods

    /// <summary>
    /// The init db.
    /// </summary>
    /// <param name="fileName">
    /// The file name.
    /// </param>
    /// <param name="password">
    /// The password.
    /// </param>
    private static void InitDb(string fileName, string password) {
      SQLiteConnection.CreateFile(fileName);
      string connString = string.Format(
        "Data Source={0};Password={1}", fileName, password);
      using (var db = new SQLiteConnection(connString)) {
        db.Open();
        using (SQLiteCommand cmd = db.CreateCommand()) {
          cmd.CommandText =
            "CREATE TABLE Voters(VoterNumber BLOB NOT NULL PRIMARY KEY DESC, " +
            "CPR BLOB UNIQUE NOT NULL, BallotStatus BLOB NOT NULL)";
          cmd.ExecuteNonQuery();
        }
      }
    }

    /// <summary>
    /// Add this encrypted voter data to the database!
    /// </summary>
    /// <param name="data">
    /// The data to add.
    /// </param>
    private void Add(EncryptedVoterData data) {
      Contract.Requires(!Equals(data, null));

      // Contract.Requires(Contract.ForAll(AllData, row => !row.CPR.Value.IsIdenticalTo(data.CPR.Value) && !row.VoterNumber.Value.IsIdenticalTo(data.VoterNumber.Value)));
      this.db.Voters.AddObject(
        Voter.CreateVoter(data.VoterNumber, data.CPR, data.BallotStatus));
      this.db.SaveChanges();
    }

    /// <summary>
    /// The dispose.
    /// </summary>
    /// <param name="disposing">
    /// The disposing.
    /// </param>
    private void Dispose(bool disposing) {
      this.isDisposed = true;
      if (disposing) this.db.Dispose();
    }

    /// <summary>
    /// The get voter.
    /// </summary>
    /// <param name="cpr">
    /// The cpr.
    /// </param>
    /// <returns>
    /// The <see cref="Voter"/>.
    /// </returns>
    private Voter GetVoter(CPR cpr) {
      CipherText encCpr = this.Parent.Crypto.AsymmetricEncrypt(
        Bytes.From(cpr.Value), this.Parent.Crypto.VoterDataEncryptionKey);

      IQueryable<Voter> res = this.db.Voters.Where(
        data =>
        data.CPR == encCpr.Value);
      return !res.Any() ? null : res.Single();
    }

    /// <summary>
    /// The get voter.
    /// </summary>
    /// <param name="voterNumber">
    /// The voter number.
    /// </param>
    /// <returns>
    /// The <see cref="Voter"/>.
    /// </returns>
    private Voter GetVoter(VoterNumber voterNumber) {
      CipherText encvoterNumber = this.Parent.Crypto.AsymmetricEncrypt(
        Bytes.From(voterNumber.Value), this.Parent.Crypto.VoterDataEncryptionKey);

      IQueryable<Voter> res = this.db.Voters.Where(
        data => data.VoterNumber ==
                encvoterNumber.Value);
      return !res.Any() ? null : res.Single();
    }

    #endregion
  }
}
