//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Aegis_DVL.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Voter> Voters
        {
            get
            {
                if ((_Voters == null))
                {
                    _Voters = base.CreateObjectSet<Voter>("Voters");
                }
                return _Voters;
            }
        }
        private ObjectSet<Voter> _Voters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Voters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVoters(Voter voter)
        {
            base.AddObject("Voters", voter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoterModel", Name="Voter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Voter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Voter object.
        /// </summary>
        /// <param name="voterId">Initial value of the VoterId property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="middleName">Initial value of the MiddleName property.</param>
        /// <param name="suffix">Initial value of the Suffix property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="eligibleDate">Initial value of the EligibleDate property.</param>
        /// <param name="absentee">Initial value of the Absentee property.</param>
        /// <param name="voted">Initial value of the Voted property.</param>
        /// <param name="returnStatus">Initial value of the ReturnStatus property.</param>
        /// <param name="ballotStyle">Initial value of the BallotStyle property.</param>
        public static Voter CreateVoter(global::System.Int32 voterId, global::System.Int32 status, global::System.String lastName, global::System.String firstName, global::System.String middleName, global::System.String suffix, global::System.DateTime dateOfBirth, global::System.DateTime eligibleDate, global::System.Boolean absentee, global::System.Boolean voted, global::System.String returnStatus, global::System.Int32 ballotStyle)
        {
            Voter voter = new Voter();
            voter.VoterId = voterId;
            voter.Status = status;
            voter.LastName = lastName;
            voter.FirstName = firstName;
            voter.MiddleName = middleName;
            voter.Suffix = suffix;
            voter.DateOfBirth = dateOfBirth;
            voter.EligibleDate = eligibleDate;
            voter.Absentee = absentee;
            voter.Voted = voted;
            voter.ReturnStatus = returnStatus;
            voter.BallotStyle = ballotStyle;
            return voter;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VoterId
        {
            get
            {
                return _VoterId;
            }
            set
            {
                if (_VoterId != value)
                {
                    OnVoterIdChanging(value);
                    ReportPropertyChanging("VoterId");
                    _VoterId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VoterId");
                    OnVoterIdChanged();
                }
            }
        }
        private global::System.Int32 _VoterId;
        partial void OnVoterIdChanging(global::System.Int32 value);
        partial void OnVoterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                OnSuffixChanging(value);
                ReportPropertyChanging("Suffix");
                _Suffix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Suffix");
                OnSuffixChanged();
            }
        }
        private global::System.String _Suffix;
        partial void OnSuffixChanging(global::System.String value);
        partial void OnSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EligibleDate
        {
            get
            {
                return _EligibleDate;
            }
            set
            {
                OnEligibleDateChanging(value);
                ReportPropertyChanging("EligibleDate");
                _EligibleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EligibleDate");
                OnEligibleDateChanged();
            }
        }
        private global::System.DateTime _EligibleDate;
        partial void OnEligibleDateChanging(global::System.DateTime value);
        partial void OnEligibleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Absentee
        {
            get
            {
                return _Absentee;
            }
            set
            {
                OnAbsenteeChanging(value);
                ReportPropertyChanging("Absentee");
                _Absentee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Absentee");
                OnAbsenteeChanged();
            }
        }
        private global::System.Boolean _Absentee;
        partial void OnAbsenteeChanging(global::System.Boolean value);
        partial void OnAbsenteeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Voted
        {
            get
            {
                return _Voted;
            }
            set
            {
                OnVotedChanging(value);
                ReportPropertyChanging("Voted");
                _Voted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Voted");
                OnVotedChanged();
            }
        }
        private global::System.Boolean _Voted;
        partial void OnVotedChanging(global::System.Boolean value);
        partial void OnVotedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReturnStatus
        {
            get
            {
                return _ReturnStatus;
            }
            set
            {
                OnReturnStatusChanging(value);
                ReportPropertyChanging("ReturnStatus");
                _ReturnStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReturnStatus");
                OnReturnStatusChanged();
            }
        }
        private global::System.String _ReturnStatus;
        partial void OnReturnStatusChanging(global::System.String value);
        partial void OnReturnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BallotStyle
        {
            get
            {
                return _BallotStyle;
            }
            set
            {
                OnBallotStyleChanging(value);
                ReportPropertyChanging("BallotStyle");
                _BallotStyle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BallotStyle");
                OnBallotStyleChanged();
            }
        }
        private global::System.Int32 _BallotStyle;
        partial void OnBallotStyleChanging(global::System.Int32 value);
        partial void OnBallotStyleChanged();

        #endregion

    
    }

    #endregion

    
}
